### ISSUE TITLE
Have DerpCAM running on windows using WLS2

### ISSUE THREAD

**Issue by ag0r** [kfoltman/DerpCAM#1]
Just thought you might like to know that I have verified this tool can run in Windows. It requires WSL2 so that the GUI can be forwarded (which requires at least windows 10 build 19044). I have only tested it using python3.9 on Ubuntu 20.04.

pyvoronoi was a little bit of a pain to get working for me, but that might just be the combination of versions I chose.

**Comment by kfoltman** [comment]
Interesting! However, I think it should also be possible to run it natively using a Windows version of Python and Qt (and other libraries). I haven't tried it myself though.
